y[1][4][0]=raw_input("Multimeter value")
 print(y[1][4][0])
 y[1][4][1]=raw_input("Multimeter value")
 print(y[1][4][1])
 y[1][4][2]=raw_input("Multimeter value")
 print(y[1][4][2])
 y[1][4][3]=raw_input("Multimeter value")
 print(y[1][4][3])
 y[1][4][4]=raw_input("Multimeter value")
 print(y[1][4][4])
 y[1][4][5]=raw_input("Multimeter value")
 print(y[1][4][5])
 y[1][4][6]=raw_input("Multimeter value")
 print(y[1][4][6])
 y[1][4][7]=raw_input("Multimeter value")
 print(y[1][4][7])